### PR TITLE
fix preAnnounceSeconds check

### LINKED ISSUE #10: BUG
This minimum timer is incorrectly informed, as it does not work in seconds, only every 1 hour. https://github.com/azerothcore/mod-server-auto-shutdown/blob/c12a4c86192e69f06361ae66480dc88d90215b45/conf/ServerAutoShutdown.conf.dist#L32

It would be interesting to customize the preceding time before sending the shutdown command.

### PR DESCRIPTION
**Pull request by garfieldbanks**
Fixes #10

### CODE REVIEW

**Comment by pangolp** [comment]
The repository is outdated. I'm going to make some changes and when it's updated, if you update your branch with the new changes, we can rerun the tests and in that way add the code to the repository

**Comment by pangolp** [comment]
After this pull request passes the tests: https://github.com/azerothcore/mod-server-auto-shutdown/pull/14 and the code can be merged, we can update this pull request, and run the tests again .

**Comment by pangolp** [comment]
It would be necessary to update the branch, with the new changes within the module, to run the tests again. When you do, please let me know. Thank you.

**Comment by Helias** [comment]
thank you for the PR!

**Pull request merged**
